# Generated by Django 5.2.8 on 2025-11-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=255)),
                ('annual_fee', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('apply_url', models.URLField(blank=True, max_length=500)),
                ('credit_range', models.CharField(blank=True, max_length=100)),
                ('rewards_rate', models.CharField(blank=True, max_length=255)),
                ('intro_offer', models.TextField(blank=True)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('pros', models.JSONField(blank=True, default=list)),
                ('cons', models.JSONField(blank=True, default=list)),
                ('best_for', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Credit Card (Firestore)',
                'verbose_name_plural': 'Credit Cards (Firestore)',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('traits', models.JSONField(blank=True, default=list)),
                ('recommended_cards', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Personality (Firestore)',
                'verbose_name_plural': 'Personalities (Firestore)',
                'managed': False,
            },
        ),
    ]
