# Generated by Django 5.2.8 on 2025-11-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('card_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('annual_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image_url', models.URLField(blank=True)),
                ('apply_url', models.URLField(blank=True)),
                ('benefits_json', models.TextField(blank=True, help_text='JSON array of benefits')),
                ('personalities_json', models.TextField(blank=True, help_text='JSON array of personality IDs')),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('personality_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji icon', max_length=10)),
            ],
            options={
                'verbose_name': 'Personality',
                'verbose_name_plural': 'Personalities',
                'managed': False,
            },
        ),
    ]
