# Generated by Django 5.2.8 on 2025-12-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalitySurvey',
            fields=[
                ('survey_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('personality_id', models.CharField(max_length=200)),
                ('responses_json', models.TextField(help_text='JSON object of question_id -> answer')),
                ('card_ids_json', models.TextField(help_text='JSON array of card IDs user has')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Personality Survey',
                'verbose_name_plural': 'Personality Surveys',
                'managed': False,
            },
        ),
    ]
