steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'walletfreak'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/walletfreak', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/walletfreak']

  # Deploy container to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'walletfreak'
      - '--image'
      - 'gcr.io/$PROJECT_ID/walletfreak'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'DJANGO_SETTINGS_MODULE=walletfreak.settings,CRON_SECRET=c2dcb5e2f6838f81956c531aee5570e2'

images:
  - 'gcr.io/$PROJECT_ID/walletfreak'

options:
  logging: CLOUD_LOGGING_ONLY
