// Auto-generated by scripts/generate-image-maps.js — do not edit manually
/* eslint-disable */
const personalityImageMap: Record<string, any> = {
  'airline-companion-chaser': require('../../../walletfreak/static/images/personalities/airline-companion-chaser.png'),
  'business-powerhouse': require('../../../walletfreak/static/images/personalities/business-powerhouse.png'),
  'cashback-pragmatist': require('../../../walletfreak/static/images/personalities/cashback-pragmatist.png'),
  'category-hunter': require('../../../walletfreak/static/images/personalities/category-hunter.png'),
  'ChatGPT Image Dec 4, 2025, 09_51_31 PM': require('../../../walletfreak/static/images/personalities/ChatGPT Image Dec 4, 2025, 09_51_31 PM.png'),
  'drugstore-freak': require('../../../walletfreak/static/images/personalities/drugstore-freak.png'),
  'family-freak': require('../../../walletfreak/static/images/personalities/family-freak.png'),
  'foodie-grocery-king': require('../../../walletfreak/static/images/personalities/foodie-grocery-king.png'),
  'gas-freak': require('../../../walletfreak/static/images/personalities/gas-freak.png'),
  'hotel-status-chaser': require('../../../walletfreak/static/images/personalities/hotel-status-chaser.png'),
  'luxury-jetsetter': require('../../../walletfreak/static/images/personalities/luxury-jetsetter.png'),
  'online-shopping-freak': require('../../../walletfreak/static/images/personalities/online-shopping-freak.png'),
  'points-strategist': require('../../../walletfreak/static/images/personalities/points-strategist.png'),
  'simple-minimalist': require('../../../walletfreak/static/images/personalities/simple-minimalist.png'),
  'streaming-freak': require('../../../walletfreak/static/images/personalities/streaming-freak.png'),
  'student-starter': require('../../../walletfreak/static/images/personalities/student-starter.png'),
  'value-traveler': require('../../../walletfreak/static/images/personalities/value-traveler.png'),
  'wallet-freak': require('../../../walletfreak/static/images/personalities/wallet-freak.png'),
  'yuppie': require('../../../walletfreak/static/images/personalities/yuppie.png'),
};

export default personalityImageMap;
