# Generated by Django 5.2.8 on 2025-12-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='experience_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('whale', 'Whale')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.CharField(choices=[('short', 'Short (< 3m)'), ('medium', 'Medium (3-7m)'), ('long', 'Long (7m+)'), ('video', 'Video Only')], default='medium', max_length=20),
        ),
    ]
