# Generated by Django 5.2.8 on 2026-01-04 14:34

from django.db import migrations



def cleanup_empty_strings(apps, schema_editor):
    StripeCustomer = apps.get_model('subscriptions', 'StripeCustomer')
    StripeCustomer.objects.filter(stripe_customer_id='').update(stripe_customer_id=None)

class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_stripecustomer_stripe_customer_id'),
    ]

    operations = [
        migrations.RunPython(cleanup_empty_strings),
    ]
