"""
Django settings for walletfreak project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import certifi

# Fix for Amadeus/SSL issues on macOS
os.environ['SSL_CERT_FILE'] = certifi.where()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6t^@gtg0h=nc31(4wrk=0-zbqfv%az=ev8ylea5g7lml^g4wvo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# Caching
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://walletfreak-99478632058.us-central1.run.app',
    'https://walletfreak.com',
    'https://www.walletfreak.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'core',
    'accounts',
    'cards',
    'dashboard',
    'blog',
    'custom_admin',
    'firestore',
    'calculators',
    'datapoints',
    'subscriptions',
    'hotel_hunter',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.FirebaseAdminMiddleware',  # Custom Firebase admin auth
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Security settings
# Allow Google Auth popups to work
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'core.admin_auth.FirebaseAdminBackend',  # Firebase admin authentication
    'django.contrib.auth.backends.ModelBackend',  # Default Django auth (fallback)
]

# ... (skip to static files section)

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'walletfreak.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.firebase_config',
                'core.context_processors.wallet_status',
            ],
        },
    },
]

WSGI_APPLICATION = 'walletfreak.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# [ACTIVE] SQLite3 Configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# [BACKUP] Cloud SQL Configuration (Commented out)
# import dj_database_url
# 
# DATABASES = {
#     'default': dj_database_url.config(
#         default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
#         conn_max_age=600,
#         ssl_require=False
#     )
# }
# if os.environ.get('DATABASE_URL'):
#     print(f"✅ Configuring Database from URL: {os.environ.get('DATABASE_URL').split('@')[1] if '@' in os.environ.get('DATABASE_URL') else 'INVALID_URL'}")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Firebase Configuration
import firebase_admin
from firebase_admin import credentials
import os

FIREBASE_CREDENTIALS_PATH = os.environ.get('GOOGLE_APPLICATION_CREDENTIALS', BASE_DIR / 'serviceAccountKey.json')

if not firebase_admin._apps:
    if FIREBASE_CREDENTIALS_PATH and os.path.exists(FIREBASE_CREDENTIALS_PATH):
        try:
            cred = credentials.Certificate(FIREBASE_CREDENTIALS_PATH)
            firebase_admin.initialize_app(cred, {
                'storageBucket': 'walletfreak-cc.firebasestorage.app'
            })
            print(f"✅ Firebase initialized successfully with credentials from {FIREBASE_CREDENTIALS_PATH}")
        except Exception as e:
            print(f"❌ Failed to initialize Firebase: {e}")
    else:
        try:
            firebase_admin.initialize_app(options={
                'storageBucket': 'walletfreak-cc.firebasestorage.app'
            })
            print("✅ Firebase initialized with default credentials")
        except Exception as e:
            print(f"❌ Failed to initialize Firebase with default credentials: {e}")

FIREBASE_CLIENT_CONFIG = {
    "apiKey": "AIzaSyDZ4JTnyOBlkXoRlR7FbiQs6nPrwRlixEM",
    "authDomain": "walletfreak-cc.firebaseapp.com",
    "projectId": "walletfreak-cc",
    "storageBucket": "walletfreak-cc.firebasestorage.app",
    "messagingSenderId": "99478632058",
    "appId": "1:99478632058:web:410490ffab3e4011426dc3",
    "measurementId": "G-DJSZXRZH6V"
}


# Authentication settings
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/wallet/'

# Email Backend (SMTP for Production/Real Testing)
# Note: Primary email sending is handled via Firestore Trigger Extension
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or 'notifications@walletfreak.com'



# Amadeus API Configuration
AMADEUS_CLIENT_ID = os.environ.get('AMADEUS_CLIENT_ID')
AMADEUS_CLIENT_SECRET = os.environ.get('AMADEUS_CLIENT_SECRET')

# Stripe Configuration
# Check if live mode is enabled (default to False)
STRIPE_LIVE_MODE = os.environ.get('STRIPE_LIVE_MODE', 'False').lower() == 'true'

if STRIPE_LIVE_MODE:
    STRIPE_PUBLIC_KEY = os.environ.get('STRIPE_LIVE_PUBLIC_KEY') or os.environ.get('STRIPE_PUBLIC_KEY')
    STRIPE_SECRET_KEY = os.environ.get('STRIPE_LIVE_SECRET_KEY') or os.environ.get('STRIPE_SECRET_KEY')
    STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_LIVE_WEBHOOK_SECRET') or os.environ.get('STRIPE_WEBHOOK_SECRET')
    STRIPE_PRICE_MONTHLY = os.environ.get('STRIPE_LIVE_PRICE_MONTHLY') or os.environ.get('STRIPE_PRICE_MONTHLY')
    STRIPE_PRICE_YEARLY = os.environ.get('STRIPE_LIVE_PRICE_YEARLY') or os.environ.get('STRIPE_PRICE_YEARLY')
else:
    STRIPE_PUBLIC_KEY = os.environ.get('STRIPE_TEST_PUBLIC_KEY') or os.environ.get('STRIPE_PUBLIC_KEY')
    STRIPE_SECRET_KEY = os.environ.get('STRIPE_TEST_SECRET_KEY') or os.environ.get('STRIPE_SECRET_KEY')
    STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_TEST_WEBHOOK_SECRET') or os.environ.get('STRIPE_WEBHOOK_SECRET')
    STRIPE_PRICE_MONTHLY = os.environ.get('STRIPE_TEST_PRICE_MONTHLY') or os.environ.get('STRIPE_PRICE_MONTHLY')
    STRIPE_PRICE_YEARLY = os.environ.get('STRIPE_TEST_PRICE_YEARLY') or os.environ.get('STRIPE_PRICE_YEARLY')


