import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';
import { colors, darkColors } from './colors';

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.primary,
    onPrimary: colors.onPrimary,
    primaryContainer: colors.primaryContainer,
    onPrimaryContainer: colors.onPrimaryContainer,
    secondary: colors.secondary,
    onSecondary: colors.onSecondary,
    secondaryContainer: colors.secondaryContainer,
    onSecondaryContainer: colors.onSecondaryContainer,
    tertiary: colors.tertiary,
    onTertiary: colors.onTertiary,
    tertiaryContainer: colors.tertiaryContainer,
    onTertiaryContainer: colors.onTertiaryContainer,
    error: colors.error,
    onError: colors.onError,
    errorContainer: colors.errorContainer,
    onErrorContainer: colors.onErrorContainer,
    surface: colors.surface,
    onSurface: colors.onSurface,
    surfaceVariant: colors.surfaceVariant,
    onSurfaceVariant: colors.onSurfaceVariant,
    outline: colors.outline,
    outlineVariant: colors.outlineVariant,
    background: colors.background,
    onBackground: colors.onBackground,
    inverseSurface: colors.inverseSurface,
    inverseOnSurface: colors.inverseOnSurface,
    inversePrimary: colors.inversePrimary,
    scrim: colors.scrim,
    elevation: {
      ...MD3LightTheme.colors.elevation,
      level1: colors.surfaceContainerLow,
      level2: colors.surfaceContainer,
      level3: colors.surfaceContainerHigh,
    },
  },
  custom: {
    surfaceContainerLow: colors.surfaceContainerLow,
    surfaceContainer: colors.surfaceContainer,
    surfaceContainerHigh: colors.surfaceContainerHigh,
    surfaceContainerHighest: colors.surfaceContainerHighest,
    success: colors.success,
    warning: colors.warning,
    info: colors.info,
    benefitEmpty: colors.benefitEmpty,
    benefitPartial: colors.benefitPartial,
    benefitFull: colors.benefitFull,
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: darkColors.primary,
    onPrimary: darkColors.onPrimary,
    primaryContainer: darkColors.primaryContainer,
    onPrimaryContainer: darkColors.onPrimaryContainer,
    secondary: darkColors.secondary,
    onSecondary: darkColors.onSecondary,
    secondaryContainer: darkColors.secondaryContainer,
    onSecondaryContainer: darkColors.onSecondaryContainer,
    tertiary: darkColors.tertiary,
    onTertiary: darkColors.onTertiary,
    tertiaryContainer: darkColors.tertiaryContainer,
    onTertiaryContainer: darkColors.onTertiaryContainer,
    error: darkColors.error,
    onError: darkColors.onError,
    errorContainer: darkColors.errorContainer,
    onErrorContainer: darkColors.onErrorContainer,
    surface: darkColors.surface,
    onSurface: darkColors.onSurface,
    surfaceVariant: darkColors.surfaceVariant,
    onSurfaceVariant: darkColors.onSurfaceVariant,
    outline: darkColors.outline,
    outlineVariant: darkColors.outlineVariant,
    background: darkColors.background,
    onBackground: darkColors.onBackground,
    inverseSurface: darkColors.inverseSurface,
    inverseOnSurface: darkColors.inverseOnSurface,
    inversePrimary: darkColors.inversePrimary,
    scrim: darkColors.scrim,
    elevation: {
      ...MD3DarkTheme.colors.elevation,
      level1: darkColors.surfaceContainerLow,
      level2: darkColors.surfaceContainer,
      level3: darkColors.surfaceContainerHigh,
    },
  },
  custom: {
    surfaceContainerLow: darkColors.surfaceContainerLow,
    surfaceContainer: darkColors.surfaceContainer,
    surfaceContainerHigh: darkColors.surfaceContainerHigh,
    surfaceContainerHighest: darkColors.surfaceContainerHighest,
    success: darkColors.success,
    warning: darkColors.warning,
    info: darkColors.info,
    benefitEmpty: darkColors.benefitEmpty,
    benefitPartial: darkColors.benefitPartial,
    benefitFull: darkColors.benefitFull,
  },
};

export { colors, darkColors } from './colors';
export { typography } from './typography';
export { spacing, borderRadius } from './spacing';
export { shadows } from './shadows';
